#possible values: DB, FS, demo
PERSISTENCY=DB

#possible values: GUI, CLI
UI_TYPE=GUI

#demo version credentials
profemail=mario.rossi@gmail.com
profpasswd=mario.rossi
studentemail=giuseppe.bianchi@gmail.com
studentpasswd=giuseppe.bianchi

#DB connection
CONNECTION_URL=jdbc:mariadb://localhost:3306/SoStudyDB
USER_DB=admin_user
USER_PASSWD=admin_user

#possible values: test, run (when value = test, demo version runs)
activity=test