PERSISTENCY=DB
UI_TYPE=GUI
profemail=mario.rossi@gmail.com
profpasswd=mario.rossi
studentemail=giuseppe.bianchi@gmail.com
studentpasswd=giuseppe.bianchi
CONNECTION_URL=jdbc:mariadb://localhost:3306/SoStudyDB
USER_DB=admin_user
USER_PASSWD=admin_user